apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-devops-app.fullname" . }}
  labels:
    app: {{ include "my-devops-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-devops-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-devops-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-devops-app.fullname" . }}
  labels:
    app: {{ include "my-devops-app.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: {{ include "my-devops-app.name" . }}
