apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-devops-app.fullname" . }}
  labels:
    app: {{ include "my-devops-app.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: {{ include "my-devops-app.name" . }}
